apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatewise.fullname" . }}-secrets
  labels:
    {{- include "gatewise.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "gatewise.postgresql.connectionString" . | quote }}
  {{- if .Values.controlPlane.license.key }}
  license-key: {{ .Values.controlPlane.license.key | quote }}
  {{- end }}
  {{- if and (not .Values.kafka.enabled) .Values.kafka.external.sasl.password }}
  kafka-password: {{ .Values.kafka.external.sasl.password | quote }}
  {{- end }}
  {{- if and (not .Values.kong.enabled) .Values.kong.external.apiKey }}
  kong-api-key: {{ .Values.kong.external.apiKey | quote }}
  {{- end }}
